### ISSUE TITLE
do you know how git behaves with `.jl.gz` files?

### ISSUE THREAD

**Issue by AlJohri** [TeamHG-Memex/json-lines#11]
two qs:

1. can git version control `jl.gz` files properly? I want to create an append only .jl.gz file and store it in git. I anticipate it being between 50-90mb which makes storing in git viable. As I append new lines to the `.jl.gz` file, will git be able to store just the diffs or new binaries each time?

2. can json-lines directly append to a `.jl.gz` file?

**Comment by lopuhin** [comment]
> As I append new lines to the .jl.gz file, will git be able to store just the diffs or new binaries each time?

From my understanding it should work, because .jl.gz is really append-only, but I never tried it.

> can json-lines directly append to a .jl.gz file?

json-lines does not provide a writer at all, but something like this should work (note `at` mode to append to existing file):

```
with gzip.open(path, 'at', encoding='utf8') as outf:
  for item in data:
    json.dump(item, outf)
    outf.write('\n')
```

**Comment by AlJohri** [comment]
thank you!
